name: FleaFinder

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
        - name: Checkout code
          uses: actions/checkout@v5
      # Setup node.js
        - name: Setup Node.js
          uses: actions/setup-node@v5
          with:
            node-version: 24
      # Install Dependencies
        - name: Install Dependencies
          run: npm install
      # Build the project
        - name: Build project
          run: npm run build
      # Deploy to github pages
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4